#!/bin/bash

# Enhanced Search Function
curl -X POST "https://api.supabase.com/v1/projects/birugqyuqhiahxvxeyqg/database/query" \
  -H "Authorization: Bearer sbp_f30783ba26b0a6ae2bba917988553bd1d5f76d97" \
  -H "Content-Type: application/json" \
  -d @- << 'EOF'
{
  "query": "CREATE OR REPLACE FUNCTION public.search_embeddings_enhanced(query_embedding vector(1536), p_domain_id UUID DEFAULT NULL, match_threshold float DEFAULT 0.7, match_count int DEFAULT 10, content_types text[] DEFAULT NULL, query_keywords text[] DEFAULT NULL, boost_recent boolean DEFAULT false) RETURNS TABLE (id UUID, page_id UUID, chunk_text text, url text, title text, metadata jsonb, base_similarity float, position_boost float, keyword_boost float, recency_boost float, content_type_boost float, final_score float) LANGUAGE plpgsql STABLE AS $$ DECLARE current_date timestamp := NOW(); BEGIN RETURN QUERY WITH scored_results AS (SELECT pe.id, pe.page_id, pe.chunk_text, COALESCE((pe.metadata->>'url')::text, sp.url) as url, COALESCE((pe.metadata->>'title')::text, sp.title) as title, pe.metadata, 1 - (pe.embedding <=> query_embedding) as base_similarity, CASE WHEN (pe.metadata->>'chunk_index')::int = 0 THEN 0.15 WHEN (pe.metadata->>'chunk_index')::int = 1 THEN 0.10 WHEN (pe.metadata->>'chunk_index')::int = 2 THEN 0.05 ELSE 0 END as position_boost, CASE WHEN query_keywords IS NOT NULL AND pe.metadata->'keywords' IS NOT NULL AND pe.metadata->'keywords' ?| query_keywords THEN 0.20 WHEN query_keywords IS NOT NULL AND pe.metadata->'entities' IS NOT NULL AND (pe.metadata->'entities'->'products' ?| query_keywords OR pe.metadata->'entities'->'brands' ?| query_keywords OR pe.metadata->'entities'->'skus' ?| query_keywords) THEN 0.25 ELSE 0 END as keyword_boost, CASE WHEN boost_recent AND pe.metadata->>'indexed_at' IS NOT NULL THEN GREATEST(0, 0.1 * (1 - EXTRACT(EPOCH FROM (current_date - (pe.metadata->>'indexed_at')::timestamp)) / (86400 * 180))) ELSE 0 END as recency_boost, CASE WHEN pe.metadata->>'content_type' = 'product' AND query_keywords IS NOT NULL AND (array_length(query_keywords, 1) > 0) THEN 0.10 WHEN pe.metadata->>'content_type' = 'faq' AND pe.chunk_text LIKE '%?%' THEN 0.05 ELSE 0 END as content_type_boost FROM page_embeddings pe INNER JOIN scraped_pages sp ON pe.page_id = sp.id WHERE (p_domain_id IS NULL OR sp.domain_id = p_domain_id) AND pe.embedding IS NOT NULL AND 1 - (pe.embedding <=> query_embedding) > match_threshold AND (content_types IS NULL OR pe.metadata->>'content_type' = ANY(content_types))), final_scored AS (SELECT *, base_similarity + position_boost + keyword_boost + recency_boost + content_type_boost as final_score FROM scored_results) SELECT id, page_id, chunk_text, url, title, metadata, base_similarity, position_boost, keyword_boost, recency_boost, content_type_boost, final_score FROM final_scored ORDER BY final_score DESC LIMIT match_count; END; $$; GRANT EXECUTE ON FUNCTION public.search_embeddings_enhanced TO service_role, authenticated, anon;"
}
EOF