name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees:
  - IDLEcreative

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide detailed information to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: I'm frustrated when... / Users need to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: Describe any alternative solutions or features you've considered
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area of the system does this feature relate to?
      options:
        - Chat Widget
        - API/Backend
        - Web Scraping
        - E-commerce Integration
        - Dashboard/UI
        - Authentication/Security
        - Analytics/Reporting
        - Performance
        - Documentation
        - DevOps/Infrastructure
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking major use case
        - High - Significantly improves workflow
        - Medium - Nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific examples of how this feature would be used
      placeholder: |
        1. As a [role], I want to [action] so that [benefit]
        2. When [scenario], I need to [action]
      value: |
        1.
        2.
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Expected Benefits
      description: What are the expected benefits of this feature?
      placeholder: |
        - Reduces time spent on...
        - Improves user experience by...
        - Enables new capability...
    validations:
      required: false

  - type: textarea
    id: technical-considerations
    attributes:
      label: Technical Considerations
      description: Any technical details, constraints, or implementation suggestions?
      placeholder: |
        - Should integrate with...
        - Must support...
        - Performance requirements...
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, wireframes, or examples from other products
      placeholder: Drag and drop images here or paste links

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or links about the feature request
      placeholder: Any additional information that might be helpful

  - type: dropdown
    id: willing-to-contribute
    attributes:
      label: Contribution
      description: Are you willing to contribute to implementing this feature?
      options:
        - Yes, I can implement this
        - Yes, I can help with testing
        - Yes, I can help with documentation
        - No, but I can provide feedback
        - No
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided a clear problem statement and proposed solution
          required: true
        - label: This feature aligns with the project's goals and architecture
          required: false
