#!/bin/bash

# This script shows the secrets you need to add to GitHub
# from your existing .env.local file

echo "========================================="
echo "GitHub Secrets to Add"
echo "========================================="
echo ""
echo "1. SECRET NAME: SUPABASE_URL"
echo "   VALUE:"
echo "   https://birugqyuqhiahxvxeyqg.supabase.co"
echo ""
echo "2. SECRET NAME: SUPABASE_SERVICE_ROLE_KEY"
echo "   VALUE:"
echo "   eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpcnVncXl1cWhpYWh4dnhleXFnIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NTc4NzE2NCwiZXhwIjoyMDcxMzYzMTY0fQ.5bw0QlkRgv_PA7iHrpWixvC31d7WZ5VYSR2JZnhsw8s"
echo ""
echo "3. SECRET NAME: DATABASE_URL"
echo "   VALUE:"
echo "   ⚠️  You need to get this from Supabase Dashboard:"
echo "   1. Go to https://app.supabase.com/project/birugqyuqhiahxvxeyqg/settings/database"
echo "   2. Look for 'Connection pooling' section"
echo "   3. Copy the 'Connection string' (Mode: Transaction)"
echo "   4. It will look like: postgresql://postgres.birugqyuqhiahxvxeyqg:[PASSWORD]@aws-0-us-west-1.pooler.supabase.com:6543/postgres"
echo ""
echo "4. SECRET NAME: MONITOR_ALERT_WEBHOOK_URL"
echo "   VALUE (placeholder for now):"
echo "   https://example.com/webhook"
echo "   OR create a real Slack webhook at https://api.slack.com/apps"
echo ""
echo "========================================="
echo "How to add to GitHub:"
echo "========================================="
echo "1. Go to: https://github.com/jamesguy/Omniops/settings/secrets/actions"
echo "2. Click 'New repository secret' for each"
echo "3. Copy the SECRET NAME and VALUE exactly as shown above"
echo "4. After adding all 4, test with: gh workflow run 'Nightly Telemetry & GDPR Validation'"
echo ""